const std::string if_default = "if(    )\n{\n    \n}";
const std::string if_knr = "if(    ){\n    \n}";
const std::string if_one_line = "if(    ) \n";
const std::string else_if_default = "else if(    )\n{\n    \n}";
const std::string else_if_knr = "else if(    ){\n    \n}";
const std::string else_if_one_line = "else if(    ) \n";
const std::string else_default = "else\n {\n}";
const std::string else_knr = "else{\n   \n}";
const std::string else_one_line = "else \n";    